// 游戏配置常量

export const GAME_CONFIG = {
  // 画布尺寸
  CANVAS_WIDTH: 450,
  CANVAS_HEIGHT: 800,
  
  // 网格
  GRID_SIZE: 40,
  
  // 玩家
  PLAYER_INITIAL_HEALTH: 3,
  PLAYER_MAX_HEALTH: 3,
  
  // 砖块
  BRICK_WIDTH: 70,
  BRICK_HEIGHT: 30,
  BRICK_SPACING: 10,
  BRICKS_PER_ROW: 5,
  BRICK_HEALTH_MULTIPLIER: 2,
  
  // 子弹
  BULLET_SPEED: 400,
  BULLET_RADIUS: 8,
  BULLET_DAMAGE: 10,
  
  // 弹珠
  MARBLE_RADIUS: 8,
  MARBLE_GRAVITY: 500,
  MARBLE_BOUNCE_DECAY: 0.85,
  MARBLE_INITIAL_SPEED_X_RANGE: [-50, 50],
  
  // 缓冲器
  BUMPER_RADIUS: 20,
  BUMPER_COOLDOWN: 500,
  
  // AOE
  AOE_MAX_RADIUS: 100,
  AOE_EXPAND_SPEED: 200,
  AOE_DAMAGE: 5,
  
  // 能量
  ENERGY_PER_MODULE: 10,
  ENERGY_FULL_SLOT_EFFICIENCY: 0.8,
  
  // 物理
  BORDER_BOUNCE_DECAY: 0.9,
  PIERCING_DAMAGE_CD: 100,
  
  // UI
  SLOT_COUNT: 3,
  SLOT_WIDTH: 100,
  SLOT_HEIGHT: 80,
  SLOT_SPACING: 20,
};

export const COLORS = {
  BACKGROUND: 0x1a1a2e,
  PLAYER: 0x00d4ff,
  BRICK_LOW_HEALTH: 0xff6b6b,
  BRICK_HIGH_HEALTH: 0xff0000,
  BULLET_NORMAL: 0x00ff00,
  BULLET_PIERCING: 0xffff00,
  BULLET_AOE: 0xff00ff,
  BUMPER: 0x4ecdc4,
  BUMPER_COOLDOWN: 0x666666,
  MARBLE: 0xffffff,
  ENERGY_BAR_BG: 0x666666,
  ENERGY_BAR_FG: 0x00ff00,
  REWARD_BUMPER: 0xffd700,
};
